### ISSUE TITLE
bbox_extract.py for Detectron2

### ISSUE THREAD

**Issue by yueyue0401** [UARK-AICV/VLTinT#1]
After installing Detectron2, I cannot find **bbox_extract.py** in any folders. Was the bbox_extract.py renamed? Thank you so much.

**Comment by Kashu7100** [comment]
Thank you for pointing that out. I updated the README.
The bbox_extract is from the fork of detectron2 (`git clone https://github.com/vhvkhoa/detectron2`).
So, instead of using facebook detectron2, please use the one from `https://github.com/vhvkhoa/detectron2`.

I am sorry for the confusion and thank you again for letting me know.
