### ISSUE TITLE
The scores for YouCookII are different.

### ISSUE THREAD

**Issue by yueyue0401** [UARK-AICV/VLTinT#3]
Hi,

I trained the model in the dataset YouCookII and used the same configuration you provided in GitHub; however, I got different scores. Especially my Cider score is much lower than your Cider score. By the way, I got very close scores in ActivityNet Captions to yours by using the configuration in GitHub. I am wondering if you use different configurations to train in these two models.

The model trained in YouCookII
METEOR | ROGUE_L | CIDEr | Bleu_4
Your Scores 
17.94 | 34.55 | 48.7 | 9.4
My Score      
17.33 | 34.18 | 44.18 | 9.21

Thank you so much for sharing the amazing code!!

**Comment by Kashu7100** [comment]
Thank you for your kind email.

In order for others to know, I am posting the same answer as the one I gave you.

>I have checked the model configuration of the YC2 model upon your request. 
I noticed that I turned off the agent feature for the YC2 since the dataset contains fewer humans in the scene.
I will attach the validation log during the training for your reference.  I think you can obtain the best result around epoch 15~20. 

Please feel free to reopen this issue to ask me any further questions you may have

**Comment by yangxingrui** [comment]
> Hi,
> 
> I trained the model in the dataset YouCookII and used the same configuration you provided in GitHub; however, I got different scores. Especially my Cider score is much lower than your Cider score. By the way, I got very close scores in ActivityNet Captions to yours by using the configuration in GitHub. I am wondering if you use different configurations to train in these two models.
> 
> The model trained in YouCookII METEOR | ROGUE_L | CIDEr | Bleu_4 Your Scores 17.94 | 34.55 | 48.7 | 9.4 My Score 17.33 | 34.18 | 44.18 | 9.21
> 
> Thank you so much for sharing the amazing code!!

Hello, do you know the reason why the indicators displayed in the paper cannot be achieved on the YouCook2 dataset? If you have solved this problem, please let me know. Thank you very much!
